vich_uploader:
    db_driver: orm

    mappings:
       noticeImagePath:
           uri_prefix: /images/notices
           upload_destination: '%kernel.project_dir%/public/images/notices'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       serviceImagePath:
           uri_prefix: /images/services
           upload_destination: '%kernel.project_dir%/public/images/services'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
